export function buildFeishuInstallerPromptHookScript(): string {
  return [
    "'use strict';",
    "const net = require('node:net');",
    "const { randomUUID } = require('node:crypto');",
    "const Module = require('node:module');",
    "const HOST = '127.0.0.1';",
    "const PORT = Number(process.env.QCLAW_FEISHU_PROMPT_PORT || '0');",
    "const SESSION_TOKEN = String(process.env.QCLAW_FEISHU_PROMPT_SESSION_TOKEN || '').trim();",
    "const STATE_KEY = Symbol.for('qclaw.feishuInstallerPromptHook');",
    "if (!globalThis[STATE_KEY]) {",
    "  globalThis[STATE_KEY] = true;",
    "  const originalLoad = Module._load;",
    "  Module._load = function patchedLoad(request, parent, isMain) {",
    "    const loaded = originalLoad.apply(this, arguments);",
    "    if (typeof request === 'string' && request.includes('inquirer')) {",
    "      return patchInquirerModule(loaded);",
    "    }",
    "    return loaded;",
    "  };",
    "}",
    "",
    "function isRecord(value) {",
    "  return Boolean(value) && typeof value === 'object' && !Array.isArray(value);",
    "}",
    "",
    "function normalizeQuestions(questions) {",
    "  return Array.isArray(questions) ? questions.filter(Boolean) : questions ? [questions] : [];",
    "}",
    "",
    "function extractAppId(question) {",
    "  const corpus = [question && question.message, question && question.prefix, question && question.suffix]",
    "    .map((value) => String(value || ''))",
    "    .join(' ');",
    "  const match = corpus.match(/(cli_[a-z0-9]+)/i);",
    "  return match ? match[1] : '';",
    "}",
    "",
    "function sendPromptRequest(question) {",
    "  if (!PORT || !SESSION_TOKEN) {",
    "    throw new Error('Qclaw structured Feishu prompt bridge is unavailable.');",
    "  }",
    "  const promptId = randomUUID();",
    "  return new Promise((resolve, reject) => {",
    "    const socket = net.createConnection({ host: HOST, port: PORT });",
    "    let settled = false;",
    "    let buffer = '';",
    "    const settle = (fn, value) => {",
    "      if (settled) return;",
    "      settled = true;",
    "      socket.destroy();",
    "      fn(value);",
    "    };",
    "    socket.on('connect', () => {",
    "      socket.write(`${JSON.stringify({",
    "        type: 'prompt',",
    "        sessionToken: SESSION_TOKEN,",
    "        promptId: '__PROMPT_ID__',",
    "        promptName: 'useExisting',",
    "        promptType: 'confirm',",
    "        defaultValue: typeof question.default === 'boolean' ? question.default : null,",
    "        appId: extractAppId(question),",
    "      }).replace('__PROMPT_ID__', promptId)}\\n`);",
    "    });",
    "    socket.on('data', (chunk) => {",
    "      buffer += String(chunk || '');",
    "      let newlineIndex = buffer.indexOf('\\n');",
    "      while (newlineIndex >= 0) {",
    "        const line = buffer.slice(0, newlineIndex).trim();",
    "        buffer = buffer.slice(newlineIndex + 1);",
    "        if (line) {",
    "          try {",
    "            const message = JSON.parse(line);",
    "            if (!message || message.promptId !== promptId) {",
    "              newlineIndex = buffer.indexOf('\\n');",
    "              continue;",
    "            }",
    "            if (message.type === 'prompt-answer') {",
    "              settle(resolve, Boolean(message.answer));",
    "              return;",
    "            }",
    "            if (message.type === 'prompt-abort') {",
    "              settle(reject, new Error(String(message.message || 'Qclaw canceled the pending Feishu prompt.')));",
    "              return;",
    "            }",
    "          } catch (error) {",
    "            settle(reject, error);",
    "            return;",
    "          }",
    "        }",
    "        newlineIndex = buffer.indexOf('\\n');",
    "      }",
    "    });",
    "    socket.on('error', (error) => settle(reject, error));",
    "    socket.on('close', () => {",
    "      if (!settled) {",
    "        settle(reject, new Error('Qclaw Feishu prompt bridge closed before answering.'));",
    "      }",
    "    });",
    "  });",
    "}",
    "",
    "function wrapPromptFunction(originalPrompt) {",
    "  if (typeof originalPrompt !== 'function' || originalPrompt.__qclawWrapped) {",
    "    return originalPrompt;",
    "  }",
    "  const wrappedPrompt = async function wrappedFeishuPrompt(questions, answers) {",
    "    const list = normalizeQuestions(questions);",
    "    const targetQuestion = list.find((question) => isRecord(question) && question.name === 'useExisting' && String(question.type || '').toLowerCase() === 'confirm');",
    "    if (!targetQuestion) {",
    "      return originalPrompt.apply(this, arguments);",
    "    }",
    "    const useExisting = await sendPromptRequest(targetQuestion);",
    "    const seededAnswers = isRecord(answers) ? { ...answers } : {};",
    "    seededAnswers.useExisting = useExisting;",
    "    const remainingQuestions = list.filter((question) => question !== targetQuestion);",
    "    if (remainingQuestions.length === 0) {",
    "      return seededAnswers;",
    "    }",
    "    const remainingAnswers = await originalPrompt.call(this, remainingQuestions, seededAnswers);",
    "    return isRecord(remainingAnswers) ? { ...seededAnswers, ...remainingAnswers } : seededAnswers;",
    "  };",
    "  Object.defineProperty(wrappedPrompt, '__qclawWrapped', { value: true });",
    "  return wrappedPrompt;",
    "}",
    "",
    "function patchCreatePromptModule(target) {",
    "  if (typeof target.createPromptModule !== 'function' || target.createPromptModule.__qclawWrapped) {",
    "    return;",
    "  }",
    "  const originalCreatePromptModule = target.createPromptModule.bind(target);",
    "  const wrappedCreatePromptModule = function wrappedCreatePromptModule() {",
    "    const promptModule = originalCreatePromptModule.apply(this, arguments);",
    "    return wrapPromptFunction(promptModule);",
    "  };",
    "  Object.defineProperty(wrappedCreatePromptModule, '__qclawWrapped', { value: true });",
    "  target.createPromptModule = wrappedCreatePromptModule;",
    "}",
    "",
    "function patchInquirerModule(target) {",
    "  if (!target || (typeof target !== 'object' && typeof target !== 'function')) {",
    "    return target;",
    "  }",
    "  if (target.prompt) {",
    "    target.prompt = wrapPromptFunction(target.prompt);",
    "  }",
    "  patchCreatePromptModule(target);",
    "  if (target.default && target.default !== target) {",
    "    patchInquirerModule(target.default);",
    "  }",
    "  return target;",
    "}",
    "",
  ].join('\n');
}
