export function buildFeishuInstallerPromptHookScript(): string {
  return [
    "'use strict';",
    "const fs = require('node:fs');",
    "const net = require('node:net');",
    "const path = require('node:path');",
    "const { randomUUID } = require('node:crypto');",
    "const Module = require('node:module');",
    "const HOST = '127.0.0.1';",
    "const PORT = Number(process.env.QCLAW_FEISHU_PROMPT_PORT || '0');",
    "const SESSION_TOKEN = String(process.env.QCLAW_FEISHU_PROMPT_SESSION_TOKEN || '').trim();",
    "const DIAG_ENABLED = String(process.env.QCLAW_FEISHU_DIAG || '').trim() === '1';",
    "const DIAG_LOG_PATH = String(process.env.QCLAW_FEISHU_DIAG_LOG_PATH || '').trim();",
    "const DIAG_SESSION_ID = String(process.env.QCLAW_FEISHU_DIAG_SESSION_ID || '').trim();",
    "const STATE_KEY = Symbol.for('qclaw.feishuInstallerPromptHook');",
    "if (!globalThis[STATE_KEY]) {",
    "  globalThis[STATE_KEY] = true;",
    "  const originalLoad = Module._load;",
    "  Module._load = function patchedLoad(request, parent, isMain) {",
    "    const loaded = originalLoad.apply(this, arguments);",
    "    if (typeof request === 'string') {",
    "      if (request.includes('inquirer')) {",
    "        return patchInquirerModule(loaded);",
    "      }",
    "      if (request.includes('feishu-auth')) {",
    "        return patchFeishuAuthModule(loaded);",
    "      }",
    "      if (request.includes('install-prompts')) {",
    "        return patchInstallPromptsModule(loaded);",
    "      }",
    "      if (request === './config' || request.endsWith('/config') || request.endsWith('/config.js') || request.includes('utils/config')) {",
    "        return patchConfigModule(loaded);",
    "      }",
    "    }",
    "    return loaded;",
    "  };",
    "}",
    "",
    "function isRecord(value) {",
    "  return Boolean(value) && typeof value === 'object' && !Array.isArray(value);",
    "}",
    "",
    "function appendDiagnosticRecord(event, fields) {",
    "  try {",
    "    if (!DIAG_ENABLED || !DIAG_LOG_PATH) return;",
    "    const payload = {",
    "      ts: new Date().toISOString(),",
    "      pid: process.pid,",
    "      source: 'installer-hook',",
    "      sessionId: DIAG_SESSION_ID || undefined,",
    "      event: String(event || '').trim() || 'unknown',",
    "      ...(isRecord(fields) ? fields : {}),",
    "    };",
    "    fs.mkdirSync(path.dirname(DIAG_LOG_PATH), { recursive: true });",
    "    fs.appendFileSync(DIAG_LOG_PATH, `${JSON.stringify(payload)}\\n`);",
    "  } catch {}",
    "}",
    "",
    "function normalizeQuestions(questions) {",
    "  return Array.isArray(questions) ? questions.filter(Boolean) : questions ? [questions] : [];",
    "}",
    "",
    "function emitDiagnostic(event, message, fields) {",
    "  // Keep diagnostics in the JSONL log only; avoid noisy terminal output.",
    "  // try {",
    "  //   console.log(`[QCLAW_DIAG] ${String(message || '')}`);",
    "  // } catch {}",
    "  appendDiagnosticRecord(event, {",
    "    message: String(message || ''),",
    "    ...(isRecord(fields) ? fields : {}),",
    "  });",
    "}",
    "",
    "function extractAppId(question) {",
    "  const corpus = [question && question.message, question && question.prefix, question && question.suffix]",
    "    .map((value) => String(value || ''))",
    "    .join(' ');",
    "  const match = corpus.match(/(cli_[a-z0-9]+)/i);",
    "  return match ? match[1] : '';",
    "}",
    "",
    "function sendInstallerEvent(payload) {",
    "  if (!PORT || !SESSION_TOKEN || !isRecord(payload)) {",
    "    return;",
    "  }",
    "  try {",
    "    const socket = net.createConnection({ host: HOST, port: PORT });",
    "    socket.on('connect', () => {",
    "      socket.end(`${JSON.stringify({ ...payload, sessionToken: SESSION_TOKEN })}\\n`);",
    "    });",
    "    socket.on('error', () => {});",
    "  } catch {}",
    "}",
    "",
    "function sendPromptRequest(question) {",
    "  if (!PORT || !SESSION_TOKEN) {",
    "    throw new Error('Qclaw structured Feishu prompt bridge is unavailable.');",
    "  }",
    "  const promptId = randomUUID();",
    "  return new Promise((resolve, reject) => {",
    "    const socket = net.createConnection({ host: HOST, port: PORT });",
    "    let settled = false;",
    "    let buffer = '';",
    "    const settle = (fn, value) => {",
    "      if (settled) return;",
    "      settled = true;",
    "      socket.destroy();",
    "      fn(value);",
    "    };",
    "    socket.on('connect', () => {",
    "      socket.write(`${JSON.stringify({",
    "        type: 'prompt',",
    "        sessionToken: SESSION_TOKEN,",
    "        promptId: '__PROMPT_ID__',",
    "        promptName: 'useExisting',",
    "        promptType: 'confirm',",
    "        defaultValue: typeof question.default === 'boolean' ? question.default : null,",
    "        appId: extractAppId(question),",
    "      }).replace('__PROMPT_ID__', promptId)}\\n`);",
    "    });",
    "    socket.on('data', (chunk) => {",
    "      buffer += String(chunk || '');",
    "      let newlineIndex = buffer.indexOf('\\n');",
    "      while (newlineIndex >= 0) {",
    "        const line = buffer.slice(0, newlineIndex).trim();",
    "        buffer = buffer.slice(newlineIndex + 1);",
    "        if (line) {",
    "          try {",
    "            const message = JSON.parse(line);",
    "            if (!message || message.promptId !== promptId) {",
    "              newlineIndex = buffer.indexOf('\\n');",
    "              continue;",
    "            }",
    "            if (message.type === 'prompt-answer') {",
    "              settle(resolve, Boolean(message.answer));",
    "              return;",
    "            }",
    "            if (message.type === 'prompt-abort') {",
    "              settle(reject, new Error(String(message.message || 'Qclaw canceled the pending Feishu prompt.')));",
    "              return;",
    "            }",
    "          } catch (error) {",
    "            settle(reject, error);",
    "            return;",
    "          }",
    "        }",
    "        newlineIndex = buffer.indexOf('\\n');",
    "      }",
    "    });",
    "    socket.on('error', (error) => settle(reject, error));",
    "    socket.on('close', () => {",
    "      if (!settled) {",
    "        settle(reject, new Error('Qclaw Feishu prompt bridge closed before answering.'));",
    "      }",
    "    });",
    "  });",
    "}",
    "",
    "function wrapPromptFunction(originalPrompt) {",
    "  if (typeof originalPrompt !== 'function' || originalPrompt.__qclawWrapped) {",
    "    return originalPrompt;",
    "  }",
    "  const wrappedPrompt = async function wrappedFeishuPrompt(questions, answers) {",
    "    const list = normalizeQuestions(questions);",
    "    const targetQuestion = list.find((question) => isRecord(question) && question.name === 'useExisting' && String(question.type || '').toLowerCase() === 'confirm');",
    "    if (!targetQuestion) {",
    "      return originalPrompt.apply(this, arguments);",
    "    }",
    "    const useExisting = await sendPromptRequest(targetQuestion);",
    "    const seededAnswers = isRecord(answers) ? { ...answers } : {};",
    "    seededAnswers.useExisting = useExisting;",
    "    const remainingQuestions = list.filter((question) => question !== targetQuestion);",
    "    if (remainingQuestions.length === 0) {",
    "      return seededAnswers;",
    "    }",
    "    const remainingAnswers = await originalPrompt.call(this, remainingQuestions, seededAnswers);",
    "    return isRecord(remainingAnswers) ? { ...seededAnswers, ...remainingAnswers } : seededAnswers;",
    "  };",
    "  Object.defineProperty(wrappedPrompt, '__qclawWrapped', { value: true });",
    "  return wrappedPrompt;",
    "}",
    "",
    "function patchFeishuAuthModule(target) {",
    "  if (!target || (typeof target !== 'object' && typeof target !== 'function')) {",
    "    return target;",
    "  }",
    "  const candidate = target.FeishuAuth || (target.default && target.default.FeishuAuth);",
    "  const proto = candidate && candidate.prototype;",
    "  if (!proto || typeof proto.poll !== 'function' || proto.poll.__qclawDiagWrapped) {",
    "    return target;",
    "  }",
    "  const originalPoll = proto.poll;",
    "  const wrappedPoll = async function wrappedFeishuPoll() {",
    "    const result = await originalPoll.apply(this, arguments);",
    "    if (isRecord(result) && result.client_id && result.client_secret) {",
    "      const userInfo = isRecord(result.user_info) ? result.user_info : null;",
    "      emitDiagnostic(",
    "        'auth-flow-success-poll',",
    "        `auth-flow success poll client_id=${String(result.client_id || '').trim()} open_id=${String(userInfo?.open_id || '').trim()} tenant_brand=${String(userInfo?.tenant_brand || '').trim()}`,",
    "        {",
    "          clientId: String(result.client_id || '').trim(),",
    "          openId: String(userInfo?.open_id || '').trim(),",
    "          tenantBrand: String(userInfo?.tenant_brand || '').trim(),",
    "        }",
    "      );",
    "      if (String(result.client_id || '').trim() && String(userInfo?.open_id || '').trim()) {",
    "        sendInstallerEvent({",
    "          type: 'auth-result',",
    "          appId: String(result.client_id || '').trim(),",
    "          openId: String(userInfo?.open_id || '').trim(),",
    "        });",
    "      }",
    "    }",
    "    return result;",
    "  };",
    "  Object.defineProperty(wrappedPoll, '__qclawDiagWrapped', { value: true });",
    "  proto.poll = wrappedPoll;",
    "  return target;",
    "}",
    "",
    "function patchInstallPromptsModule(target) {",
    "  if (!target || (typeof target !== 'object' && typeof target !== 'function')) {",
    "    return target;",
    "  }",
    "  const originalRunInstallAuthFlow = target.runInstallAuthFlow;",
    "  if (typeof originalRunInstallAuthFlow !== 'function' || originalRunInstallAuthFlow.__qclawDiagWrapped) {",
    "    return target;",
    "  }",
    "  const wrappedRunInstallAuthFlow = async function wrappedRunInstallAuthFlow() {",
    "    const result = await originalRunInstallAuthFlow.apply(this, arguments);",
    "    if (isRecord(result)) {",
    "      const userInfo = isRecord(result.userInfo) ? result.userInfo : null;",
    "      const appId = String(result.appId || '').trim();",
    "      const openId = String(userInfo?.openId || '').trim();",
    "      const domain = String(result.domain || '').trim();",
    "      emitDiagnostic(",
    "        'run-install-auth-flow-result',",
    "        `runInstallAuthFlow result isExisting=${Boolean(result.isExisting)} appId=${String(result.appId || '').trim()} domain=${String(result.domain || '').trim()} openId=${String(userInfo?.openId || '').trim()}`,",
    "        {",
    "          isExisting: Boolean(result.isExisting),",
    "          appId: String(result.appId || '').trim(),",
    "          domain: String(result.domain || '').trim(),",
    "          openId: String(userInfo?.openId || '').trim(),",
    "        }",
    "      );",
    "      if (appId && openId) {",
    "        sendInstallerEvent({",
    "          type: 'auth-result',",
    "          appId,",
    "          openId,",
    "          isExisting: Boolean(result.isExisting),",
    "          domain: domain || undefined,",
    "        });",
    "      }",
    "    } else {",
    "      emitDiagnostic('run-install-auth-flow-result-missing', 'runInstallAuthFlow result missing or non-object');",
    "    }",
    "    return result;",
    "  };",
    "  Object.defineProperty(wrappedRunInstallAuthFlow, '__qclawDiagWrapped', { value: true });",
    "  target.runInstallAuthFlow = wrappedRunInstallAuthFlow;",
    "  return target;",
    "}",
    "",
    "function patchConfigModule(target) {",
    "  if (!target || (typeof target !== 'object' && typeof target !== 'function')) {",
    "    return target;",
    "  }",
    "  const originalWriteConfig = target.writeConfig;",
    "  if (typeof originalWriteConfig !== 'function' || originalWriteConfig.__qclawDiagWrapped) {",
    "    return target;",
    "  }",
    "  const wrappedWriteConfig = async function wrappedWriteConfig(config) {",
    "    const channels = isRecord(config) && isRecord(config.channels) ? config.channels : null;",
    "    const feishu = channels && isRecord(channels.feishu) ? channels.feishu : null;",
    "    const appId = String(feishu?.appId || '').trim();",
    "    const dmPolicy = String(feishu?.dmPolicy || '').trim();",
    "    const groupPolicy = String(feishu?.groupPolicy || '').trim();",
    "    const allowFromCount = Array.isArray(feishu?.allowFrom) ? feishu.allowFrom.length : 0;",
    "    const configPath = typeof target.getConfigPath === 'function' ? String(target.getConfigPath() || '').trim() : '';",
    "    emitDiagnostic(",
    "      'config-write-start',",
    "      `config.write start appId=${appId} dmPolicy=${dmPolicy} groupPolicy=${groupPolicy} allowFromCount=${allowFromCount} configPath=${configPath}`,",
    "      { appId, dmPolicy, groupPolicy, allowFromCount, configPath }",
    "    );",
    "    const result = await originalWriteConfig.apply(this, arguments);",
    "    emitDiagnostic(",
    "      'config-write-complete',",
    "      `config.write complete appId=${appId} configPath=${configPath}`,",
    "      { appId, configPath }",
    "    );",
    "    return result;",
    "  };",
    "  Object.defineProperty(wrappedWriteConfig, '__qclawDiagWrapped', { value: true });",
    "  target.writeConfig = wrappedWriteConfig;",
    "  return target;",
    "}",
    "",
    "function patchCreatePromptModule(target) {",
    "  if (typeof target.createPromptModule !== 'function' || target.createPromptModule.__qclawWrapped) {",
    "    return;",
    "  }",
    "  const originalCreatePromptModule = target.createPromptModule.bind(target);",
    "  const wrappedCreatePromptModule = function wrappedCreatePromptModule() {",
    "    const promptModule = originalCreatePromptModule.apply(this, arguments);",
    "    return wrapPromptFunction(promptModule);",
    "  };",
    "  Object.defineProperty(wrappedCreatePromptModule, '__qclawWrapped', { value: true });",
    "  target.createPromptModule = wrappedCreatePromptModule;",
    "}",
    "",
    "function patchInquirerModule(target) {",
    "  if (!target || (typeof target !== 'object' && typeof target !== 'function')) {",
    "    return target;",
    "  }",
    "  if (target.prompt) {",
    "    target.prompt = wrapPromptFunction(target.prompt);",
    "  }",
    "  patchCreatePromptModule(target);",
    "  if (target.default && target.default !== target) {",
    "    patchInquirerModule(target.default);",
    "  }",
    "  return target;",
    "}",
    "",
  ].join('\n')
}
